const STORAGE_KEY='dartscore_v3_state';
const HISTORY_KEY='dartscore_v3_history';
let state={gameType:501,inRule:'master',outRule:'double',options:{checkout:true,average:true,saveThrows:true,dailyHigh:true},players:[],active:0,turn:[],modifier:null,gameId:null,startedAt:null,finished:false};
let history=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');
const $=id=>document.getElementById(id);
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));localStorage.setItem(HISTORY_KEY,JSON.stringify(history));}
function load(){const s=localStorage.getItem(STORAGE_KEY);if(s){try{state=JSON.parse(s)}catch{}} if(!state.players?.length) startGame(['Marius','Dag Arne'],501,'master','double',false);}
function playerTemplate(name){return{name,score:Number(state.gameType),in:false,darts:0,totalScore:0,throws:0,high:0,n180:0,n140:0,n100:0,yellow:0,helmet:0,winner:false};}
function startGame(names,gameType,inRule,outRule,doSave=true){state.gameType=Number(gameType);state.inRule=inRule;state.outRule=outRule;state.players=names.slice(0,8).map(n=>playerTemplate(n.trim())).filter(p=>p.name);if(state.players.length<2)state.players=[playerTemplate('Spiller 1'),playerTemplate('Spiller 2')];state.active=0;state.turn=[];state.modifier=null;state.gameId='K'+Date.now();state.startedAt=new Date().toISOString();state.finished=false;if(doSave)save();render();}
function dartValue(mult,num){if(mult==='M')return 0;const m=mult==='D'?2:mult==='T'?3:1;return m*num;}
function dartLabel(mult,num,score){if(mult==='M')return 'M';return `${mult||'S'}${num}${score===0?'=0':''}`;}
function isOpening(d){return d.mult==='D'||d.mult==='T';}
function isValidOut(d){if(state.outRule==='single')return true;if(state.outRule==='double')return d.mult==='D' && d.num!==25;if(state.outRule==='master')return d.mult==='D'||d.mult==='T';return false;}
function addDart(num){if(state.finished)return;let p=state.players[state.active];let mult=state.modifier||'S';if(num==='M'){mult='M';num=0} let raw=dartValue(mult,num);let score=raw;
 if(state.inRule==='master'&&!p.in){ if(isOpening({mult,num})){p.in=true}else{score=0} }
 state.turn.push({mult,num,score,raw,label:dartLabel(mult,num,score),scoreBefore:p.score});state.modifier=null;
 if(state.turn.length===3) commitTurn(); render(); save();}
function commitTurn(){let p=state.players[state.active];const before=p.score;const total=state.turn.reduce((a,d)=>a+d.score,0);const after=before-total;const last=state.turn[state.turn.length-1];let bust=false,win=false;
 if(after<0 || after===1){bust=true}
 else if(after===0){ if(isValidOut(last)){win=true}else bust=true }
 if(!bust){p.score=after;p.totalScore+=total;p.darts+=state.turn.length;p.throws++;p.high=Math.max(p.high,total);if(total===180)p.n180++;if(total>=140)p.n140++;if(total>=100)p.n100++; if(win){p.winner=true;state.finished=true}}
 const record={gameId:state.gameId,ts:new Date().toISOString(),player:p.name,roundNo:history.filter(h=>h.gameId===state.gameId&&h.player===p.name).length+1,darts:state.turn.map(d=>d.label),sum:bust?0:total,rawTotal:total,before,after:bust?before:p.score,bust,win,gameType:state.gameType,inRule:state.inRule,outRule:state.outRule,players:state.players.map(x=>x.name)};
 if(state.options.saveThrows)history.push(record);
 state.turn=[]; if(!state.finished)state.active=(state.active+1)%state.players.length;}
function undoDart(){if(state.turn.length){const d=state.turn.pop();let p=state.players[state.active]; if(state.inRule==='master'&&p.in&&isOpening(d)){ const hasEarlierOpening=history.some(h=>h.gameId===state.gameId&&h.player===p.name&&h.darts.some(x=>/^D|^T/.test(x))); if(!hasEarlierOpening) p.in=false;} render();save();}}
function undoThrow(){const rec=[...history].reverse().find(h=>h.gameId===state.gameId);if(!rec)return; const idx=history.lastIndexOf(rec);history.splice(idx,1);const p=state.players.find(x=>x.name===rec.player);if(p){p.score=rec.before;p.winner=false;state.finished=false;p.throws=Math.max(0,p.throws-1);p.darts=Math.max(0,p.darts-3);p.totalScore=Math.max(0,p.totalScore-(rec.bust?0:rec.sum));recalcPlayerStats(p)}state.active=state.players.findIndex(x=>x.name===rec.player);state.turn=[];render();save();}
function recalcPlayerStats(p){const rs=history.filter(h=>h.gameId===state.gameId&&h.player===p.name);p.high=0;p.n180=0;p.n140=0;p.n100=0;p.in=state.inRule==='single';for(const r of rs){p.high=Math.max(p.high,r.sum);if(r.sum===180)p.n180++;if(r.sum>=140)p.n140++;if(r.sum>=100)p.n100++;if(r.darts.some(x=>/^D|^T/.test(x)))p.in=true}}
function avg(p){return p.darts?((p.totalScore/p.darts)*3).toFixed(1):'0.0'}
function checkout(score){const simple={170:'T20 T20 Bull',167:'T20 T19 Bull',164:'T20 T18 Bull',161:'T20 T17 Bull',160:'T20 T20 D20',158:'T20 T20 D19',157:'T20 T19 D20',156:'T20 T20 D18',155:'T20 T19 D19',154:'T20 T18 D20',153:'T20 T19 D18',152:'T20 T20 D16',151:'T20 T17 D20',150:'T20 T18 D18',140:'T20 T20 D10',120:'T20 20 D20',100:'T20 D20',80:'T20 D10',60:'20 D20',50:'Bull',40:'D20',32:'D16',24:'D12',16:'D8',8:'D4',4:'D2',2:'D1'};return simple[score]|| (score<=170?'Se egen checkout':'–');}
function dailyHigh(){const today=new Date().toISOString().slice(0,10);const rows=history.filter(h=>h.ts.slice(0,10)===today);let best=rows.sort((a,b)=>b.sum-a.sum)[0];return best||null;}
function setView(view){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(view+'View').classList.add('active');if(view==='history')renderHistory();if(view==='stats')renderStats();}
function render(){renderLabels();renderPlayers();renderActive();renderPad();}
function renderLabels(){ $('gameTypeLabel').textContent=state.gameType; $('inRuleLabel').textContent=state.inRule==='master'?'Master In':'Single In'; $('outRuleLabel').textContent=state.outRule==='double'?'Double Out':state.outRule==='master'?'Master Out':'Single Out'; const best=dailyHigh(); $('dailyHigh').textContent=best?best.sum:0; $('dailyHighPlayer').textContent=best?best.player:'Ingen kast ennå';}
function renderPlayers(){const grid=$('playersGrid');const n=state.players.length;grid.style.setProperty('--player-cols', n<=4?n:4);grid.innerHTML=state.players.map((p,i)=>`<div class="player-card ${i===state.active?'active':''}"><div class="player-top"><div class="player-name">${p.name}</div><div>${p.winner?'🏆':''}</div></div><div class="player-score">${p.score}</div><div class="player-meta"><div>Avg<strong>${avg(p)}</strong></div><div>180<strong>${p.n180}</strong></div><div>High<strong>${p.high}</strong></div><div>Gult<strong>${p.yellow}</strong></div><div>Hjelm<strong>${p.helmet}</strong></div><div>In<strong>${p.in?'Ja':'Nei'}</strong></div></div></div>`).join('');}
function renderActive(){const p=state.players[state.active];$('activeName').textContent=p?.name||'–';$('activeScore').textContent=p?.score||0;$('turnDarts').textContent=[0,1,2].map(i=>`Pil ${i+1}: ${state.turn[i]?.label||'–'}`).join(' · ');$('turnTotal').textContent='Runde: '+state.turn.reduce((a,d)=>a+d.score,0);$('checkoutSuggestion').textContent=state.options.checkout&&p?checkout(p.score):'–';$('message').textContent=state.finished?'Kampen er ferdig. Start nytt spill eller angre kast.':(state.modifier?`${state.modifier} er valgt. Trykk tall eller trykk ${state.modifier} igjen for å slå av.`:'Trykk tall direkte for single. D/T kan slås av og på.');}
function renderPad(){const pad=$('numberPad');const nums=[25,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1];pad.innerHTML=nums.map(n=>`<button class="num-btn ${n>=20?'hot':''}" data-num="${n}">${n}</button>`).join('');$('doubleBtn').classList.toggle('active',state.modifier==='D');$('tripleBtn').classList.toggle('active',state.modifier==='T');}
function renderHistory(){const games=[...new Set(history.map(h=>h.gameId))].reverse();$('historyList').innerHTML=games.map(g=>{const rows=history.filter(h=>h.gameId===g);const last=rows[rows.length-1];const winner=rows.find(r=>r.win)?.player||'–';return `<div class="game-item" data-game="${g}"><strong>${g}</strong><br>${new Date(rows[0].ts).toLocaleString('no-NO')}<br>Vinner: ${winner}<br>Kast: ${rows.length}</div>`}).join('')||'Ingen historikk ennå.';document.querySelectorAll('.game-item').forEach(el=>el.onclick=()=>showGameDetail(el.dataset.game));}
function showGameDetail(gameId){const rows=history.filter(h=>h.gameId===gameId);$('historyDetail').innerHTML=`<h2>${gameId}</h2><table class="throw-table"><thead><tr><th>Tid</th><th>Spiller</th><th>Piler</th><th>Sum</th><th>Før</th><th>Etter</th><th>Status</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${new Date(r.ts).toLocaleTimeString('no-NO')}</td><td>${r.player}</td><td>${r.darts.join(' · ')}</td><td>${r.sum}</td><td>${r.before}</td><td>${r.after}</td><td>${r.win?'Vinn':r.bust?'Bust':''}</td></tr>`).join('')}</tbody></table>`;}
function renderStats(){const names=[...new Set(history.map(h=>h.player))];$('statsGrid').innerHTML=names.map(name=>{const rs=history.filter(h=>h.player===name);const total=rs.reduce((a,r)=>a+r.sum,0);const darts=rs.length*3;const high=Math.max(0,...rs.map(r=>r.sum));return `<div class="stat-card"><h2>${name}</h2><div class="stat-line"><span>Average</span><strong>${darts?((total/darts)*3).toFixed(1):'0.0'}</strong></div><div class="stat-line"><span>Høyeste kast</span><strong>${high}</strong></div><div class="stat-line"><span>180</span><strong>${rs.filter(r=>r.sum===180).length}</strong></div><div class="stat-line"><span>140+</span><strong>${rs.filter(r=>r.sum>=140).length}</strong></div><div class="stat-line"><span>100+</span><strong>${rs.filter(r=>r.sum>=100).length}</strong></div><div class="stat-line"><span>Vinn</span><strong>${rs.filter(r=>r.win).length}</strong></div></div>`}).join('')||'Ingen statistikk ennå.';}
function exportCsv(){const header=['gameId','tid','spiller','piler','sum','score_for','score_etter','bust','vinner','spilltype','in','out'];const rows=history.map(r=>[r.gameId,r.ts,r.player,r.darts.join(' '),r.sum,r.before,r.after,r.bust,r.win,r.gameType,r.inRule,r.outRule]);const csv=[header,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='dart-score-historikk.csv';a.click();}
document.addEventListener('click',e=>{const b=e.target.closest('button'); if(!b)return; if(b.classList.contains('tab'))setView(b.dataset.view); if(b.dataset.num)addDart(Number(b.dataset.num));});
$('doubleBtn').onclick=()=>{state.modifier=state.modifier==='D'?null:'D';render();};$('tripleBtn').onclick=()=>{state.modifier=state.modifier==='T'?null:'T';render();};$('missBtn').onclick=()=>addDart('M');$('undoDartBtn').onclick=undoDart;$('undoThrowBtn').onclick=undoThrow;$('newGameBtn').onclick=()=>setView('setup');$('yellowBtn').onclick=()=>{state.players[state.active].yellow++;render();save();};$('helmetBtn').onclick=()=>{state.players[state.active].helmet++;render();save();};$('startGameBtn').onclick=()=>{const names=$('playersInput').value.split('\n').map(x=>x.trim()).filter(Boolean);startGame(names,document.querySelector('input[name="gameType"]:checked').value,document.querySelector('input[name="inRule"]:checked').value,document.querySelector('input[name="outRule"]:checked').value);setView('game');};$('exportCsvBtn').onclick=exportCsv;$('clearHistoryBtn').onclick=()=>{if(confirm('Nullstille all historikk?')){history=[];save();renderHistory();renderStats();render();}};
if('serviceWorker' in navigator) navigator.serviceWorker.register('service-worker.js');
load();render();
